/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppMovimentacoesRouteImport } from './routes/_app.movimentacoes'
import { Route as AppImportarRouteImport } from './routes/_app.importar'
import { Route as AppEventosRouteImport } from './routes/_app.eventos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAdiantamentosRouteImport } from './routes/_app.adiantamentos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppMovimentacoesRoute = AppMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRoute = AppImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdiantamentosRoute = AppAdiantamentosRouteImport.update({
  id: '/adiantamentos',
  path: '/adiantamentos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/adiantamentos': typeof AppAdiantamentosRoute
  '/dashboard': typeof AppDashboardRoute
  '/eventos': typeof AppEventosRoute
  '/importar': typeof AppImportarRoute
  '/movimentacoes': typeof AppMovimentacoesRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/adiantamentos': typeof AppAdiantamentosRoute
  '/dashboard': typeof AppDashboardRoute
  '/eventos': typeof AppEventosRoute
  '/importar': typeof AppImportarRoute
  '/movimentacoes': typeof AppMovimentacoesRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/adiantamentos': typeof AppAdiantamentosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/eventos': typeof AppEventosRoute
  '/_app/importar': typeof AppImportarRoute
  '/_app/movimentacoes': typeof AppMovimentacoesRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/adiantamentos'
    | '/dashboard'
    | '/eventos'
    | '/importar'
    | '/movimentacoes'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/adiantamentos'
    | '/dashboard'
    | '/eventos'
    | '/importar'
    | '/movimentacoes'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/adiantamentos'
    | '/_app/dashboard'
    | '/_app/eventos'
    | '/_app/importar'
    | '/_app/movimentacoes'
    | '/_app/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movimentacoes': {
      id: '/_app/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AppMovimentacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importar': {
      id: '/_app/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AppImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventos': {
      id: '/_app/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/adiantamentos': {
      id: '/_app/adiantamentos'
      path: '/adiantamentos'
      fullPath: '/adiantamentos'
      preLoaderRoute: typeof AppAdiantamentosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdiantamentosRoute: typeof AppAdiantamentosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventosRoute: typeof AppEventosRoute
  AppImportarRoute: typeof AppImportarRoute
  AppMovimentacoesRoute: typeof AppMovimentacoesRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdiantamentosRoute: AppAdiantamentosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventosRoute: AppEventosRoute,
  AppImportarRoute: AppImportarRoute,
  AppMovimentacoesRoute: AppMovimentacoesRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
